# Generated by Django 5.1.2 on 2025-05-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_image_delete_contact_delete_galleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='image',
        ),
    ]
